language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: PHPCS=1

    - php: 7
      env: PHPCS=1

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./src; fi"
